### ISSUE TITLE
Instalación y configuración de Heroku.

### ISSUE THREAD

**Issue by MiguelAngelCifredo** [sos-2016-02/sandbox#4]

**Comment by tuxayo** [comment]
No hay que poner esto en el repositorio "sandbox" hay que crear un repositorio llamado "sos-2016-02"

**Comment by MiguelAngelCifredo** [comment]
Debes renombrar poniendo SOS en minúsculas !!!

**Comment by tuxayo** [comment]
Dona

**Comment by tuxayo** [comment]
Cierro porque esta incluida en sos-2016-02/sos-2016-02#5
